#configfile: /home/nvidia/catkin_workspace/src/whi_pose_registration/config/pose_registration.yaml
feature_file: /home/nvidia/catkin_workspace/src/whi_tool_create_pcd_pattern/config/features1.yaml
pcd_file_path: /home/nvidia/catkin_workspace/src/whi_tool_create_pcd_pattern/pcd/
pcd_file_prefix: getscan
feature_range: [2, -2, 1, -2]   # xmax  xmin  ymax  ymin
map_frame: odom
base_link_frame: base_link
scan_topic: /scan
laser_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 180.0] # [x, y, z, roll, pitch, yaw]
laser_frame: laser
